In [14]:
# Загружаем библиотеки
import numpy as np # работа с векторами
import matplotlib.pyplot as plt # рисовать графики
import pandas as pd # для работы с матрицами
import os as os #для смены директории

In [15]:
# Установим директорию для загрузки данных для модели
os.chdir('S:/hse/data_analysis/python')

In [63]:
# загружаем данные
names = ['book_tod', 'book_dow', 'book_category', 'book_staff', 'last_category', 'last_staff', 'last_day_services', 'last_receipt_tot', 'last_dow', 'last_tod', 'last_noshow', 'last_prod_flag', 'last_cumrev', 'last_cumbook', 'last_cumstyle','last_cumcolor','last_cumprod','last_cumcancel','last_cumnoshow','recency','noshow']
nsh = pd.read_csv('hair_salon_no_show_wrangled_df.csv') 

In [64]:
nsh.head()

Unnamed: 0   book_tod   book_dow book_category book_staff last_category  \
0           0  afternoon  Wednesday         STYLE         JJ           NaN   
1           1    morning  Wednesday         COLOR     JOANNE           NaN   
2           2        NaN  Wednesday         STYLE         JJ         COLOR   
3           3  afternoon   Thursday         STYLE      KELLY           NaN   
4           4    evening   Saturday         STYLE      KELLY         STYLE   

  last_staff  last_day_services  last_receipt_tot   last_dow   ...     \
0        NaN                  0               0.0        NaN   ...      
1        NaN                  0               0.0        NaN   ...      
2     JOANNE                  2             262.0  Wednesday   ...      
3        NaN                  0               0.0        NaN   ...      
4      KELLY                  1              35.0   Thursday   ...      

  last_prod_flag  last_cumrev  last_cumbook  last_cumstyle  last_cumcolor  \
0              0            0             0              0              0   
1              0            0             0              0              0   
2              1          262             2              1              1   
3              0            0             0              0              0   
4              0           35             1              1              0   

   last_cumprod  last_cumcancel  last_cumnoshow  noshow  recency  
0             0               0               0       0        0  
1             0               0               0       0        0  
2             2               0               0       0       35  
3             0               0               0       0        0  
4             0               0               0       0        9  

[5 rows x 22 columns]

In [21]:
len(nsh)

1952

In [94]:
#из-за того, что при построения модели логистической регрессии она не обрабатывала категориальные переменные типа string, 
# я просто от них избавлюсь и сделаю датасет только из переменных, значения которых обозначены числами
# на самом деле string переменные следовало бы перекодировать и использовать в модели
nsh1 = nsh[['last_day_services','last_receipt_tot','last_noshow','last_prod_flag','last_cumrev','last_cumbook','last_cumstyle','last_cumcolor','last_cumprod','last_cumcancel','last_cumnoshow','recency','noshow']]
names1 = ['last_day_services', 'last_receipt_tot', 'last_noshow','last_prod_flag','last_cumrev','last_cumbook','last_cumstyle','last_cumcolor','last_cumprod','last_cumcancel','last_cumnoshow','recency','noshow']

In [95]:
nsh1.head()

last_day_services  last_receipt_tot  last_noshow  last_prod_flag  \
0                  0               0.0            0               0   
1                  0               0.0            0               0   
2                  2             262.0            0               1   
3                  0               0.0            0               0   
4                  1              35.0            0               0   

   last_cumrev  last_cumbook  last_cumstyle  last_cumcolor  last_cumprod  \
0            0             0              0              0             0   
1            0             0              0              0             0   
2          262             2              1              1             2   
3            0             0              0              0             0   
4           35             1              1              0             0   

   last_cumcancel  last_cumnoshow  recency  noshow  
0               0               0        0       0  
1               0               0        0       0  
2               0               0       35       0  
3               0               0        0       0  
4               0               0        9       0

In [96]:
X = nsh1.iloc[:, 0:11].values
y = nsh1.iloc[:,12].values

In [97]:
print(X)

[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  2. 262.   0. ...   2.   0.   0.]
 ...
 [  1.  30.   0. ...   0.   0.   0.]
 [  1.  50.   0. ...   0.   1.   0.]
 [  1.  50.   0. ...   0.   1.   0.]]


In [98]:
print(y)

[0 0 0 ... 0 0 0]


In [99]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)

In [100]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

In [101]:
# логистическая регрессия
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
logreg.score(X_train, y_train), logreg.score(X_test, y_test)

C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


(0.8823981552651806, 0.8863287250384024)

In [102]:
# с регуляризацией
logreg2 = LogisticRegression(C=4)
logreg2.fit(X_train, y_train)
logreg2.score(X_train, y_train), logreg2.score(X_test, y_test)

C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


(0.8831667947732513, 0.8878648233486943)

In [103]:
# дерево
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier()
tree.fit(X_train, y_train)
tree.score(X_train, y_train), tree.score(X_test, y_test)

(0.9400461183704842, 0.8678955453149002)

In [104]:
from sklearn.ensemble import VotingClassifier
modelVote = VotingClassifier(estimators=[('lr', logreg), ('dt', tree), ('lrreg', logreg2)], voting='hard')
modelVote.fit(X_train,y_train)
modelVote.score(X_train,y_train), modelVote.score(X_test,y_test)

C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


(0.8831667947732513, 0.8878648233486943)

In [105]:
pred1=tree.predict(X_test)
pred2=logreg.predict(X_test)
pred3=logreg2.predict(X_test)

final = modelVote.predict(X_test)
pred1[:3], pred2[:3], pred3[:3], final[:3]

(array([0, 0, 0], dtype=int64),
 array([0, 0, 0], dtype=int64),
 array([0, 0, 0], dtype=int64),
 array([0, 0, 0], dtype=int64))

In [106]:
# среднее
pred1=tree.predict_proba(X_test)
pred2=logreg.predict_proba(X_test)
pred3=logreg2.predict_proba(X_test)

final=(pred1+pred2+pred3)/3
pred1[:3], pred2[:3], pred3[:3], final[:3]

(array([[0.9264, 0.0736],
        [0.5   , 0.5   ],
        [0.8   , 0.2   ]]), array([[0.915115  , 0.084885  ],
        [0.91748789, 0.08251211],
        [0.89064625, 0.10935375]]), array([[0.91813767, 0.08186233],
        [0.92088871, 0.07911129],
        [0.89121971, 0.10878029]]), array([[0.91988423, 0.08011577],
        [0.77945886, 0.22054114],
        [0.86062199, 0.13937801]]))

In [108]:
from sklearn.ensemble import BaggingClassifier
from sklearn import model_selection
modelBag = BaggingClassifier(base_estimator=logreg, n_estimators=100, random_state=5)
results = model_selection.cross_val_score(modelBag, X_train, y_train, cv=3)
# результаты кросс-валидации
results

C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.K

C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.K

C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.K

C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.K

C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.K

C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.K

C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.K

array([0.87788018, 0.88248848, 0.88452656])

In [109]:
results.mean()

0.8816317408286417

In [110]:
# без кросс-валидации
modelBag.fit(X_train, y_train)
modelBag.score(X_train, y_train), modelBag.score(X_test, y_test)

C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.K

C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.K

(0.8831667947732513, 0.8878648233486943)

In [111]:
from sklearn.ensemble import RandomForestClassifier
modelRF = RandomForestClassifier(n_estimators=100, max_features=5)
modelRF.fit(X_train, y_train)
modelRF.score(X_train, y_train), modelRF.score(X_test, y_test)

(0.9400461183704842, 0.8878648233486943)

In [112]:
from sklearn.ensemble import ExtraTreesClassifier
modelET = ExtraTreesClassifier(n_estimators=100, max_features=5)
modelET.fit(X_train, y_train)
modelET.score(X_train, y_train), modelET.score(X_test, y_test)

(0.9400461183704842, 0.8786482334869432)

In [113]:
from sklearn.ensemble import AdaBoostClassifier
modelAB = AdaBoostClassifier(base_estimator=logreg, n_estimators=100)
modelAB.fit(X_train, y_train)
modelAB.score(X_train, y_train), modelAB.score(X_test, y_test)

C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.K

C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Anastasia.K

(0.8808608762490392, 0.8832565284178188)

In [114]:
from sklearn.ensemble import GradientBoostingClassifier
modelGB = GradientBoostingClassifier(n_estimators=100)
modelGB.fit(X_train, y_train)
modelGB.score(X_train, y_train), modelGB.score(X_test, y_test)

(0.9200614911606456, 0.8863287250384024)

In [115]:
pred1_train = pd.DataFrame(logreg2.predict(X_train))
pred2_train = pd.DataFrame(tree.predict(X_train))
pred1_test = pd.DataFrame(logreg2.predict(X_test))
pred2_test = pd.DataFrame(tree.predict(X_test))

data_train = pd.concat([pred1_train, pred2_train], axis=1)
data_test = pd.concat([pred1_test, pred2_test], axis=1)

modelSt = LogisticRegression()
modelSt.fit(data_train,y_train)
modelSt.score(data_train, y_train), modelSt.score(data_test, y_test)

C:\Users\Anastasia.Kincharova\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


(0.9400461183704842, 0.8678955453149002)

In [116]:
tree.feature_importances_

array([0.02896261, 0.12718687, 0.00886957, 0.02908303, 0.27729035,
       0.08467433, 0.15173237, 0.08609977, 0.00515796, 0.05921477,
       0.14172838])

In [122]:
names1

['last_day_services',
 'last_receipt_tot',
 'last_noshow',
 'last_prod_flag',
 'last_cumrev',
 'last_cumbook',
 'last_cumstyle',
 'last_cumcolor',
 'last_cumprod',
 'last_cumcancel',
 'last_cumnoshow',
 'recency',
 'noshow']

In [59]:
import eli5

In [124]:
#здесь не уверена, что правильно выводятся имена переменных - нет ли путаницы с names1?
feat_imp_tree = eli5.explain_weights_df(tree, feature_names=names1[0:11])
feat_imp_tree

feature    weight
0         last_cumrev  0.277290
1       last_cumstyle  0.151732
2      last_cumnoshow  0.141728
3    last_receipt_tot  0.127187
4       last_cumcolor  0.086100
5        last_cumbook  0.084674
6      last_cumcancel  0.059215
7      last_prod_flag  0.029083
8   last_day_services  0.028963
9         last_noshow  0.008870
10       last_cumprod  0.005158

In [127]:
eli5.explain_weights_df(modelRF, feature_names=names1[0:11])

feature    weight       std
0         last_cumrev  0.268005  0.057119
1    last_receipt_tot  0.146501  0.033777
2      last_cumnoshow  0.117361  0.050544
3       last_cumstyle  0.110189  0.036286
4        last_cumbook  0.097147  0.042836
5       last_cumcolor  0.070392  0.034927
6      last_cumcancel  0.060713  0.031409
7        last_cumprod  0.058251  0.035417
8   last_day_services  0.034073  0.019033
9         last_noshow  0.027827  0.029019
10     last_prod_flag  0.009541  0.010732

In [128]:
modelRF.feature_importances_

array([0.03407252, 0.14650119, 0.02782693, 0.00954116, 0.26800516,
       0.09714703, 0.11018899, 0.07039188, 0.05825132, 0.06071275,
       0.11736107])

In [130]:
all_features = pd.DataFrame(data=[tree.feature_importances_ for tree in 
                                     modelRF],
                               columns=names1[0:11])

In [131]:
all_features.head()

last_day_services  last_receipt_tot  last_noshow  last_prod_flag  \
0           0.044993          0.166059     0.000250        0.005992   
1           0.025370          0.163852     0.012720        0.020227   
2           0.019076          0.144097     0.001775        0.001115   
3           0.026835          0.102799     0.000000        0.022324   
4           0.015149          0.134798     0.020603        0.000000   

   last_cumrev  last_cumbook  last_cumstyle  last_cumcolor  last_cumprod  \
0     0.230672      0.132040       0.093222       0.087338      0.035141   
1     0.179223      0.222810       0.115423       0.061861      0.042787   
2     0.326968      0.193832       0.074459       0.018273      0.040974   
3     0.194329      0.071583       0.095784       0.070893      0.136851   
4     0.309590      0.073502       0.089234       0.078379      0.028868   

   last_cumcancel  last_cumnoshow  
0        0.066811        0.137482  
1        0.042631        0.113096  
2        0.016654        0.162775  
3        0.090727        0.187875  
4        0.155015        0.094862

In [132]:
all_features.mean()

last_day_services    0.034073
last_receipt_tot     0.146501
last_noshow          0.027827
last_prod_flag       0.009541
last_cumrev          0.268005
last_cumbook         0.097147
last_cumstyle        0.110189
last_cumcolor        0.070392
last_cumprod         0.058251
last_cumcancel       0.060713
last_cumnoshow       0.117361
dtype: float64

In [133]:
all_features.std()

last_day_services    0.019129
last_receipt_tot     0.033947
last_noshow          0.029165
last_prod_flag       0.010786
last_cumrev          0.057406
last_cumbook         0.043052
last_cumstyle        0.036469
last_cumcolor        0.035103
last_cumprod         0.035595
last_cumcancel       0.031567
last_cumnoshow       0.050799
dtype: float64

In [136]:
eli5.explain_weights_df(logreg, feature_names=names1[0:11])

target            feature    weight
0        1        last_noshow  1.118389
1        1     last_cumcancel  0.580574
2        1      last_cumstyle  0.448013
3        1  last_day_services  0.050141
4        1        last_cumrev  0.005446
5        1   last_receipt_tot  0.004188
6        1       last_cumprod -0.011782
7        1      last_cumcolor -0.015511
8        1     last_cumnoshow -0.095607
9        1     last_prod_flag -0.313949
10       1       last_cumbook -0.745450
11       1             <BIAS> -2.377752

In [137]:
logreg.coef_

array([[ 0.0501407 ,  0.00418803,  1.11838927, -0.31394858,  0.00544552,
        -0.74545029,  0.44801274, -0.01551131, -0.01178191,  0.58057392,
        -0.09560668]])

In [138]:
logreg.intercept_

array([-2.3777524])

In [140]:
eli5.explain_weights_df(modelGB, feature_names=names1[0:11])

feature    weight       std
0         last_cumrev  0.241393  0.195627
1      last_cumnoshow  0.230780  0.170561
2    last_receipt_tot  0.113052  0.244653
3        last_cumbook  0.101326  0.159040
4       last_cumstyle  0.100828  0.188131
5       last_cumcolor  0.081583  0.083504
6        last_cumprod  0.038683  0.098301
7   last_day_services  0.030812  0.107574
8      last_cumcancel  0.029659  0.081638
9         last_noshow  0.021431  0.113077
10     last_prod_flag  0.010452  0.010799

In [148]:
#feature_names=???
eli5.explain_weights_df(modelSt, )

target feature    weight
0       1      x1  5.157886
1       1      x0 -0.063421
2       1  <BIAS> -2.589771

In [149]:
#adaboost, которая не работала прошлый раз
from eli5.sklearn import PermutationImportance
permAB = PermutationImportance(modelAB).fit(X_test, y_test)
eli5.explain_weights_df(permAB, feature_names=names[0:11])

feature        weight       std
0       last_category  4.055300e-02  0.004076
1          last_staff  3.686636e-02  0.003222
2   last_day_services  2.642089e-02  0.003812
3            last_tod  7.373272e-03  0.003556
4    last_receipt_tot  2.220446e-17  0.001683
5            last_dow  0.000000e+00  0.000000
6          book_staff  0.000000e+00  0.000000
7            book_dow -6.144393e-04  0.000753
8            book_tod -9.216590e-04  0.001229
9       book_category -1.228879e-03  0.001791
10        last_noshow -3.072197e-03  0.000000

In [150]:
eli5.show_weights(permAB)

In [153]:
eli5.show_weights(permAB, feature_names=names1[0:11])

In [154]:
permRF = PermutationImportance(modelRF).fit(X_test, y_test)
eli5.show_weights(permRF, feature_names=names[0:11])